/**
 * Note Model
 *
 * Stores user notes - both manual and AI-generated.
 * Notes can optionally be linked to a transcript time range.
 */

import mongoose, { Schema, Document, Model } from "mongoose";
import { embedNote } from "../services/embedding.service";

// =============================================================================
// Interfaces
// =============================================================================

export interface NoteI extends Document {
  userId: string;
  title: string;
  summary: string;
  content: string;
  isStarred: boolean; // Legacy — use isFavourite instead
  isFavourite: boolean;
  isArchived: boolean;
  isTrashed: boolean;
  isAIGenerated: boolean; // Whether this note was generated by AI or created manually
  date: string; // Folder date in YYYY-MM-DD format (which day this note belongs to)
  folderId?: string; // Optional folder assignment
  embedding: number[];
  transcriptRange?: {
    startTime: Date;
    endTime: Date;
  };
  /**
   * Timestamp of the last automatic regeneration (e.g. when a conversation
   * reopened and the note was re-generated to cover the extended range).
   * Compared against `updatedAt` to detect manual user edits: if
   * `updatedAt > lastAutoGeneratedAt`, the user has touched the note since
   * the last auto-write and we won't overwrite their work on the next
   * regeneration. Null for notes from before this field existed — treat as
   * "don't overwrite" to be safe.
   */
  lastAutoGeneratedAt: Date | null;
  createdAt: Date;
  updatedAt: Date;
}

// =============================================================================
// Schema
// =============================================================================

const NoteSchema = new Schema<NoteI>(
  {
    userId: { type: String, required: true, index: true },
    title: { type: String, required: true },
    summary: { type: String, default: "" },
    content: { type: String, default: "" },
    isStarred: { type: Boolean, default: false }, // Legacy — use isFavourite
    isFavourite: { type: Boolean, default: false },
    isArchived: { type: Boolean, default: false },
    isTrashed: { type: Boolean, default: false },
    isAIGenerated: { type: Boolean, default: false }, // Whether AI generated or manual
    date: { type: String, required: true, index: true }, // Folder date in YYYY-MM-DD format
    folderId: { type: String, default: null }, // Optional folder assignment
    embedding: { type: [Number], default: [] },
    transcriptRange: {
      startTime: { type: Date },
      endTime: { type: Date },
    },
    lastAutoGeneratedAt: { type: Date, default: null },
  },
  { timestamps: true },
);

// Index for efficient user queries sorted by creation date
NoteSchema.index({ userId: 1, createdAt: -1 });

// =============================================================================
// Model
// =============================================================================

export const Note: Model<NoteI> =
  mongoose.models.Note || mongoose.model<NoteI>("Note", NoteSchema);

// =============================================================================
// Helper Functions
// =============================================================================

/**
 * Create a new note
 */
export async function createNote(
  userId: string,
  data: {
    title: string;
    content?: string;
    summary?: string;
    date: string; // Required: folder date in YYYY-MM-DD format
    isAIGenerated?: boolean;
    transcriptRange?: { startTime: Date; endTime: Date };
  },
): Promise<NoteI> {
  const isAI = data.isAIGenerated ?? false;
  const note = await Note.create({
    userId,
    title: data.title,
    content: data.content || "",
    summary: data.summary || "",
    date: data.date,
    isAIGenerated: isAI,
    transcriptRange: data.transcriptRange,
  });

  // Anchor lastAutoGeneratedAt to the same updatedAt Mongoose just wrote
  // so any subsequent isNoteUserEdited() check returns false until the
  // user actually edits. Done in a separate write with timestamps disabled
  // so updatedAt itself doesn't shift.
  if (isAI) {
    await Note.updateOne(
      { _id: note._id },
      { $set: { lastAutoGeneratedAt: note.updatedAt } },
      { timestamps: false },
    );
    note.lastAutoGeneratedAt = note.updatedAt;
  }

  // Fire-and-forget: generate embedding async
  embedNote(note._id!.toString(), data.title, data.content || "").catch(() => {});

  return note;
}

/**
 * Get all notes for a user
 */
export async function getNotes(userId: string): Promise<NoteI[]> {
  return Note.find({ userId }).sort({ createdAt: -1 });
}

/**
 * Get a single note by ID
 */
export async function getNoteById(
  userId: string,
  noteId: string,
): Promise<NoteI | null> {
  return Note.findOne({ _id: noteId, userId });
}

/**
 * Update a note. Treated as a USER EDIT — bumps `updatedAt` without
 * touching `lastAutoGeneratedAt`, so subsequent regenerate-in-place calls
 * will detect the edit and refuse to overwrite.
 */
export async function updateNote(
  userId: string,
  noteId: string,
  data: Partial<{
    title: string;
    content: string;
    summary: string;
    isFavourite: boolean;
    isArchived: boolean;
    isTrashed: boolean;
    folderId: string | null;
  }>,
): Promise<NoteI | null> {
  const note = await Note.findOneAndUpdate(
    { _id: noteId, userId },
    { $set: data },
    { new: true },
  );

  // Fire-and-forget: regenerate embedding if title or content changed
  if (note && (data.title !== undefined || data.content !== undefined)) {
    embedNote(noteId, note.title, note.content).catch(() => {});
  }

  return note;
}

/**
 * Auto-heal write — bumps `updatedAt` like a normal write, but also
 * re-anchors `lastAutoGeneratedAt` to the same value so isNoteUserEdited()
 * keeps returning false. Use for background cleanups (markdown
 * normalization, title recovery) that aren't user-initiated edits.
 */
export async function updateNoteAuto(
  userId: string,
  noteId: string,
  data: Partial<{
    title: string;
    content: string;
    summary: string;
  }>,
): Promise<NoteI | null> {
  const note = await Note.findOneAndUpdate(
    { _id: noteId, userId },
    { $set: data },
    { new: true },
  );
  if (!note) return null;
  await Note.updateOne(
    { _id: noteId, userId },
    { $set: { lastAutoGeneratedAt: note.updatedAt } },
    { timestamps: false },
  );
  note.lastAutoGeneratedAt = note.updatedAt;
  if (data.title !== undefined || data.content !== undefined) {
    embedNote(noteId, note.title, note.content).catch(() => {});
  }
  return note;
}

/**
 * Overwrite an AI-generated note's content/title from a fresh regeneration.
 * Bumps lastAutoGeneratedAt so the next user edit becomes detectable.
 */
export async function regenerateNoteContent(
  userId: string,
  noteId: string,
  data: { title: string; content: string; transcriptRange?: { startTime: Date; endTime: Date } },
): Promise<NoteI | null> {
  const note = await Note.findOneAndUpdate(
    { _id: noteId, userId },
    {
      $set: {
        title: data.title,
        content: data.content,
        ...(data.transcriptRange ? { transcriptRange: data.transcriptRange } : {}),
      },
    },
    { new: true },
  );
  if (!note) return null;
  // Anchor lastAutoGeneratedAt to the same updatedAt Mongoose just wrote so
  // the next isNoteUserEdited() check returns false. Done in a separate
  // write with timestamps disabled so updatedAt itself doesn't shift.
  await Note.updateOne(
    { _id: noteId, userId },
    { $set: { lastAutoGeneratedAt: note.updatedAt } },
    { timestamps: false },
  );
  note.lastAutoGeneratedAt = note.updatedAt;
  embedNote(noteId, note.title, note.content).catch(() => {});
  return note;
}

/**
 * True if the user has manually edited the note since its last
 * auto-generation. Null `lastAutoGeneratedAt` (legacy notes) is treated as
 * "edited" — i.e. don't overwrite — to avoid blowing away user work on
 * notes from before this field existed.
 *
 * Uses a 2-second tolerance so background writes that happen right after
 * the auto-write (e.g. embedding jobs that previously bumped updatedAt)
 * don't get misread as user edits.
 */
const USER_EDIT_TOLERANCE_MS = 2_000;
export function isNoteUserEdited(note: Pick<NoteI, "updatedAt" | "lastAutoGeneratedAt">): boolean {
  if (!note.lastAutoGeneratedAt) return true;
  return note.updatedAt.getTime() - note.lastAutoGeneratedAt.getTime() > USER_EDIT_TOLERANCE_MS;
}

/**
 * Delete a note
 */
export async function deleteNote(
  userId: string,
  noteId: string,
): Promise<boolean> {
  const result = await Note.deleteOne({ _id: noteId, userId });
  return result.deletedCount > 0;
}

/**
 * Get notes by date range (based on createdAt)
 */
export async function getNotesByDateRange(
  userId: string,
  startDate: Date,
  endDate: Date,
): Promise<NoteI[]> {
  return Note.find({
    userId,
    createdAt: { $gte: startDate, $lte: endDate },
  }).sort({ createdAt: -1 });
}

/**
 * Delete all notes for a specific date (YYYY-MM-DD)
 * Returns the number of deleted notes
 */
/**
 * Unassign all notes from a folder (set folderId to null)
 */
/**
 * Delete all trashed notes for a user
 */
export async function deleteTrashedNotes(userId: string): Promise<number> {
  const result = await Note.deleteMany({ userId, isTrashed: true });
  return result.deletedCount;
}

export async function unassignNotesFromFolder(
  userId: string,
  folderId: string,
): Promise<number> {
  const result = await Note.updateMany(
    { userId, folderId },
    { $set: { folderId: null } },
  );
  return result.modifiedCount;
}

/**
 * Delete all notes for a specific date (YYYY-MM-DD)
 * Returns the number of deleted notes
 */
export async function deleteNotesByDate(
  userId: string,
  date: string,
): Promise<number> {
  const result = await Note.deleteMany({
    userId,
    date: date,
  });

  return result.deletedCount;
}
